version: 2

models:
  - name: int_flights_kpis
    description: "Intermediate flight data with calculated KPIs including delay categories, time of day analysis, and duration metrics."
    columns:
      - name: flight_date
        description: "The date of the flight"
        tests:
          - not_null
      - name: flight_status
        description: "Current status of the flight"
      - name: dep_iata
        description: "Departure airport IATA code"
        tests:
          - not_null
      - name: arr_iata
        description: "Arrival airport IATA code"
        tests:
          - not_null
      - name: airline_iata
        description: "Airline IATA code"
      - name: flight_number
        description: "Flight number"
      - name: flight_iata_full
        description: "Full flight code (airline IATA + flight number)"
      - name: dep_delay_min
        description: "Departure delay in minutes"
      - name: day_of_week
        description: "Day of week (0=Sunday, 6=Saturday)"
      - name: day_of_week_name
        description: "Name of the day of week"
      - name: is_weekend
        description: "Boolean flag indicating if flight is on weekend"
      - name: dep_hour
        description: "Hour of scheduled departure (0-23)"
      - name: time_of_day
        description: "Categorized time of day (Morning, Afternoon, Evening, Night)"
        tests:
          - accepted_values:
              values: ['Morning', 'Afternoon', 'Evening', 'Night']
      - name: scheduled_duration_min
        description: "Scheduled flight duration in minutes"
      - name: actual_duration_min
        description: "Actual flight duration in minutes"
      - name: duration_diff_min
        description: "Difference between actual and scheduled duration"
      - name: delay_category
        description: "Categorized delay level"
        tests:
          - accepted_values:
              values: ['unknown', 'severe_delay', 'moderate_delay', 'minor_delay', 'ontime', 'early']
      - name: is_delayed_15
        description: "Boolean flag if delay exceeds 15 minutes"
      - name: avg_delay
        description: "Average delay for aggregation purposes"

  - name: int_flights
    description: "Final intermediate flight model with deduplicated records and 7-day rolling average delay calculation."
    columns:
      - name: flight_key
        description: "Surrogate key combining flight_iata_full and flight_date"
        tests:
          - unique
          - not_null
      - name: flight_iata_full
        description: "Full flight code"
        tests:
          - not_null
      - name: flight_date
        description: "The date of the flight"
        tests:
          - not_null
      - name: dep_iata
        description: "Departure airport IATA code"
        tests:
          - not_null
      - name: arr_iata
        description: "Arrival airport IATA code"
        tests:
          - not_null
      - name: airline_iata
        description: "Airline IATA code"
      - name: flight_number
        description: "Flight number"
      - name: dep_scheduled
        description: "Scheduled departure timestamp"
      - name: dep_actual
        description: "Actual departure timestamp"
      - name: arr_scheduled
        description: "Scheduled arrival timestamp"
      - name: arr_actual
        description: "Actual arrival timestamp"
      - name: flight_status
        description: "Flight status"
      - name: dep_delay_min
        description: "Departure delay in minutes"
      - name: arr_delay_min
        description: "Arrival delay in minutes"
      - name: day_of_week
        description: "Day of week number"
      - name: day_of_week_name
        description: "Day of week name"
      - name: is_weekend
        description: "Weekend flag"
      - name: dep_hour
        description: "Departure hour"
      - name: time_of_day
        description: "Time of day category"
      - name: scheduled_duration_min
        description: "Scheduled duration in minutes"
      - name: actual_duration_min
        description: "Actual duration in minutes"
      - name: duration_diff_min
        description: "Duration difference in minutes"
      - name: delay_category
        description: "Delay category"
      - name: is_delayed_15
        description: "Delayed over 15 minutes flag"
      - name: avg_delay_7d
        description: "7-day rolling average delay for the route"
